apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reply-service
  namespace: ai-demo
  labels:
    app: reply-service
spec:
  template:
    spec:
      containers:
        - image: quay.io/kevent-mesh/ai-demo-reply-service:main
          ports:
            - containerPort: 8080
