apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reply-service-trigger-1
  namespace: ai-demo
spec:
  broker: predictions-broker
  filter:
    attributes:
      type: eventmesh.ai-demo.prediction
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: reply-service-internal-1
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reply-service-trigger-2
  namespace: ai-demo
spec:
  broker: predictions-broker
  filter:
    attributes:
      type: eventmesh.ai-demo.prediction
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: reply-service-internal-2
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reply-service-trigger-3
  namespace: ai-demo
spec:
  broker: predictions-broker
  filter:
    attributes:
      type: eventmesh.ai-demo.prediction
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: reply-service-internal-3
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reply-service-trigger-4
  namespace: ai-demo
spec:
  broker: predictions-broker
  filter:
    attributes:
      type: eventmesh.ai-demo.prediction
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: reply-service-internal-4
