apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-cop/gitops-catalog/serverless-operator/operator/overlays/stable?ref=main
  - github.com/redhat-cop/gitops-catalog/serverless-operator/instance/knative-serving/overlays/default?ref=main
  - github.com/redhat-cop/gitops-catalog/serverless-operator/instance/knative-eventing/base?ref=main
  - knative-kafka.yaml
  - minio-operator-namespace.yaml
  - minio-operator-operatorgroup.yaml
  - minio-operator-subscription.yaml
  - minio-storage-configuration.yaml
  - minio-tenant.yaml
  - minio-console-route.yaml
  - ai-demo-namespace.yaml
  - minio-webhook-source/event-display-service.yaml
  - minio-webhook-source/ksvc.yaml
  - minio-webhook-source/broker.yaml
  - upload-service/service.yaml
  - ui-service/configmap.yaml
  - ui-service/service.yaml
  - reply-service/service.yaml
  - reply-service/trigger.yaml
  - prediction-service/service.yaml
  - prediction-service/trigger.yaml
  - inference-service/service.yaml
  - analytics-service

