apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio-operator
  labels:
    app: minio
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: '9000'
    prometheus.io/scrape: 'true'
spec:
  serviceMetadata:
    consoleServiceAnnotations: {}
    consoleServiceLabels: {}
    minioServiceAnnotations: {}
    minioServiceLabels: {}
  certConfig: {}
  users:
    - name: storage-user
  buckets:
    - name: ai-demo
  env: []
  imagePullSecret: {}
  configuration:
    name: storage-configuration
  pools:
    - containerSecurityContext: {}
      securityContext: {}
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      name: pool-0
      servers: 2
      volumesPerServer: 2
  features:
    domains: {}
    bucketDNS: false
  externalCaCertSecret: []
  externalCertSecret: []
  mountPath: /export
  podManagementPolicy: Parallel
  priorityClassName: ''
  requestAutoCert: true
  serviceAccountName: ''
  subPath: ''
  prometheusOperator: true
