apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: analytics-service-feedbacks-trigger
  namespace: ai-demo
spec:
  broker: analytics-broker
  filter:
    attributes:
      type: com.knative.dev.feedback.event
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: analytics-service
    uri: /feedbacks
