{
 "title": "admin overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Negative feedback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Negative feedback",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT feedback, upload_id FROM feedbacks WHERE feedback <= 2 ORDER BY created_on LIMIT 50"
    }
   ]
  },
  { "title": "Model confidence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Model confidence over time (positive cases) - higher is better",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT  created_on AS \"time\", probability FROM predictions WHERE  $__timeFilter(created_on) AND probability >= 0.5 ORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Model confidence over time (negative cases) - lower is better",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT  created_on AS \"time\",  probability FROM predictions WHERE  $__timeFilter(created_on) AND probability < 0.5 ORDER BY 1,2"
    }
   ]
  },
  { "title": "Users feedback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Feedback over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT created_on AS \"time\", feedback FROM \"feedbacks\" ORDER BY 1"
    }
   ]
  }
 ]
}