apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "grafana"
spec:
  route:
    spec: { }
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: ai-demo
      admin_password: ai-demo
