apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: analytics-service-predictions-trigger
  namespace: ai-demo
spec:
  broker: predictions-broker
  filter:
    attributes:
      type: eventmesh.ai-demo.prediction
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: analytics-service
    uri: /predictions
