apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: inference-service
  namespace: ai-demo
  labels:
    app: inference-service
spec:
  template:
    spec:
      containers:
        - image: quay.io/kevent-mesh/ai-demo-inference-service:main
          ports:
            - containerPort: 8501
