# TODO: make a deployment
apiVersion: v1
kind: Pod
metadata:
  name: inference-service
  namespace: ai-demo
  labels:
    app: inference-service
spec:
  containers:
    - name: inference-service
      image: quay.io/kevent-mesh/ai-demo-inference-service-v1:main
      imagePullPolicy: Always
      ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: ai-demo
spec:
  selector:
    app: inference-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
---
# TODO: remove
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: inference-service
  namespace: ai-demo
spec:
  to:
    kind: Service
    name: inference-service
  port:
    targetPort: 8501
  wildcardPolicy: None
