apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prediction-service
  namespace: ai-demo
  labels:
    app: prediction-service
spec:
  template:
    spec:
      containers:
        - image: quay.io/kevent-mesh/ai-demo-prediction-service:main
          ports:
            - containerPort: 8080
          env:
            - name: SOURCE_DECLARATION
              value: "prediction-service"
            - name: S3_ENDPOINT_URL
              value: https://minio.minio-operator.svc.cluster.local
            - name: S3_ACCESS_KEY_ID
              value: minio
            - name: S3_ACCESS_KEY_SECRET
              value: minio1234
            - name: S3_ACCESS_SSL_VERIFY
              value: "false"
            - name: S3_BUCKET_NAME
              value: ai-demo
