apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: minio-webhook-source
  namespace: ai-demo
  labels:
    app: minio-webhook-source
spec:
  template:
    spec:
      containers:
        - image: quay.io/kevent-mesh/ai-demo-minio-webhook-source:latest
          ports:
            - containerPort: 5000
          env:
            - name: SOURCE_DECLARATION
              value: "minio-webhook-source"
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: minio-webhook-source
  namespace: ai-demo
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    selector:
      matchLabels:
        app: minio-webhook-source
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: predictions-broker
